Panoply (#215)
* EU: LOCALONLY Fix FTP URL in UI

* EU: Favico

* EU: Expand velvet kmer values

Used for training

* EU: LOCALONLY fix loading of tools

* EU: Add local phinch site in lieu of GIE

* EU: add SEEK data source

* EU: Adding support for juicer hic and test data for it (#49)
EU: Add scool format (#56)

* EU: add OMICS-DI

* UPSTREAM?: Update recommendations.py

* EU: Add ARC Gitlab File Source Plugin

* TEMP: Temporary disable Release Notes icon

Until the release notes are out.

* TEMP: Try fixing ITs callback

* add ITs changes from 23.0_europe to 23.1_europe

* unpin tensorflow to make it work with python 3.11

* TEMP: Log errors occurring while refreshing user tokens as debug messages

Temporary solution to avoid spamming Sentry with exceptions like this one https://sentry.galaxyproject.org/organizations/galaxy/issues/125247/events/64073692e52f49afac1f4eb38c174f84/.

* update outputs (#187)

* add outputs from jupyter (#188)

* Divand (#189)

* add outputs from jupyter

* add default notebook

* Source (#190)

* update outputs

* add default notebook

* Update datatypes_conf.xml.sample add docx type (#192)

* Update datatypes_conf.xml.sample add docx type

* Update datatypes_conf.xml.sample docx -> Docx

* Update binary.py add docx type

* Update binary.py

* Update datatypes_conf.xml.sample

---------

Co-authored-by: Björn Grüning <bjoern@gruenings.eu>

* Source (#191)

* update outputs

* add default notebook

* add an inputs folder

* Change Sentry error reporting plug-in

- Use the tool's name (tool id without version) as issue title. This should merge reports for all versions of a tool. Report any other extra information in the contexts.

- Submit Galaxy Job error reports with level "error" rather than "info".

- Do not include the user's email in the "job" context. It is redundant because it was already being included in the "user" context.

- Move the user's feedback message to a new "feedback" context.

- Report the user's information as actual Sentry user information rather than a "user" context.

- Change existing tags. Use "tool" for `job.tool_id`, `tool.name` for the tool's name (tool id without version) and `tool.version` for the tool's version.

- Add a tag informing of whether the user provided feedback or not so that intentional bug reports can be quickly found.

* Remove "request" context

The request context's "url" field is filled with the text "*deprecated attribute, URL not filled in by server*".

* Ignore anonymous users

* Update interactivetool_qgis.xml

ping @Marie59

* change premission of output folder

* change permissions for the app user

* add interactivetool ilastik

* Rename tools/interactive/interactive/interactivetool_ilastik.xml to tools/interactive/interactivetool_ilastik.xml

* use directory where app user has rw access (#196)

* Update interactivetool_odv.xml add tabular input file for odv txt file (#197)

* Update interactivetool_odv.xml add tabular input file for odv txt file

* Update interactivetool_odv.xml add label and help infos for text files

* add multiple input (#198)

* fix ODV

* small fix odv (#199)

* new version of qgis (#200)

* Create interactivetool_genenotebook.xml (#201)

* add support for Zarr datatype (#203)

* add support for Zarr datatype

* added test file for testing Zarr datatype

* remove get_mime function for Zarr
as we do not have proper mimetype for zarr

* add avivator_zarr as display application

* Add support for prefixing calls to HTCondor binaries to the HTCondor runner

Define an optional parameter `prefix` for the HTCondor job runner that prepends the parameter value to all calls to HTCondor binaries, such as `condor_submit`, `condor_rm` or `condor_ssh_to_job`.

* Add support for overriding HTCondor commands to the HTCondor runner

Define three optional parameters `condor_rm_cmd`, `condor_ssh_to_job_cmd`, `condor_submit_cmd` that override calls to `condor_rm`, `condor_ssh_to_job` and `condor_submit` with the parameters' values.

In addition, the runner now invokes the commands through a shell. This allows tricks such as passing the `condor_*` invocations as arguments to other commands, or performing other tasks before the calls.

* Fix `condor_submit` and `condor_stop` docstrings

* Update HTCondor runner documentation

Make it clear that the `prefix` is followed by the command without any spaces in between, and thus adding a trailing space to `prefix` is recommended.

* Add new inputs (#204)

* Add new inputs

* frenglish mistake

* new docker version

* Odv : fix path (#205)

* Add new inputs

* frenglish mistake

* new docker version

* Fix broken paths

* fix permission issue for RStudio

* Replace ELIXIR AAI button with Life Science login (#206)

* LS Login button - Update managers.py

ELIXIR AAI (orange) -> LS Login (white/blue)

* LS Login button - Update oidc_backends_config.xml.sample

ELIXIR AAI (orange) -> LS Login (white/blue)

* EU: LOCALONLY Fix FTP URL in UI

* EU: Favico

* EU: Expand velvet kmer values

Used for training

* EU: LOCALONLY fix loading of tools

* EU: Add local phinch site in lieu of GIE

* EU: add SEEK data source

* EU: Adding support for juicer hic and test data for it (#49)
EU: Add scool format (#56)

* EU: add OMICS-DI

* UPSTREAM?: Update recommendations.py

* EU: Add ARC Gitlab File Source Plugin

* TEMP: Temporary disable Release Notes icon

Until the release notes are out.

* TEMP: Try fixing ITs callback

* add ITs changes from 23.0_europe to 23.1_europe

* unpin tensorflow to make it work with python 3.11

* TEMP: Log errors occurring while refreshing user tokens as debug messages

Temporary solution to avoid spamming Sentry with exceptions like this one https://sentry.galaxyproject.org/organizations/galaxy/issues/125247/events/64073692e52f49afac1f4eb38c174f84/.

* update outputs (#187)

* add outputs from jupyter (#188)

* Divand (#189)

* add outputs from jupyter

* add default notebook

* Source (#190)

* update outputs

* add default notebook

* Update datatypes_conf.xml.sample add docx type (#192)

* Update datatypes_conf.xml.sample add docx type

* Update datatypes_conf.xml.sample docx -> Docx

* Update binary.py add docx type

* Update binary.py

* Update datatypes_conf.xml.sample

---------

Co-authored-by: Björn Grüning <bjoern@gruenings.eu>

* Source (#191)

* update outputs

* add default notebook

* add an inputs folder

* Change Sentry error reporting plug-in

- Use the tool's name (tool id without version) as issue title. This should merge reports for all versions of a tool. Report any other extra information in the contexts.

- Submit Galaxy Job error reports with level "error" rather than "info".

- Do not include the user's email in the "job" context. It is redundant because it was already being included in the "user" context.

- Move the user's feedback message to a new "feedback" context.

- Report the user's information as actual Sentry user information rather than a "user" context.

- Change existing tags. Use "tool" for `job.tool_id`, `tool.name` for the tool's name (tool id without version) and `tool.version` for the tool's version.

- Add a tag informing of whether the user provided feedback or not so that intentional bug reports can be quickly found.

* Remove "request" context

The request context's "url" field is filled with the text "*deprecated attribute, URL not filled in by server*".

* Ignore anonymous users

* Update interactivetool_qgis.xml

ping @Marie59

* change premission of output folder

* change permissions for the app user

* add interactivetool ilastik

* Rename tools/interactive/interactive/interactivetool_ilastik.xml to tools/interactive/interactivetool_ilastik.xml

* use directory where app user has rw access (#196)

* Update interactivetool_odv.xml add tabular input file for odv txt file (#197)

* Update interactivetool_odv.xml add tabular input file for odv txt file

* Update interactivetool_odv.xml add label and help infos for text files

* add multiple input (#198)

* fix ODV

* small fix odv (#199)

* new version of qgis (#200)

* Create interactivetool_genenotebook.xml (#201)

* add support for Zarr datatype (#203)

* add support for Zarr datatype

* added test file for testing Zarr datatype

* remove get_mime function for Zarr
as we do not have proper mimetype for zarr

* add avivator_zarr as display application

* Add support for prefixing calls to HTCondor binaries to the HTCondor runner

Define an optional parameter `prefix` for the HTCondor job runner that prepends the parameter value to all calls to HTCondor binaries, such as `condor_submit`, `condor_rm` or `condor_ssh_to_job`.

* Add support for overriding HTCondor commands to the HTCondor runner

Define three optional parameters `condor_rm_cmd`, `condor_ssh_to_job_cmd`, `condor_submit_cmd` that override calls to `condor_rm`, `condor_ssh_to_job` and `condor_submit` with the parameters' values.

In addition, the runner now invokes the commands through a shell. This allows tricks such as passing the `condor_*` invocations as arguments to other commands, or performing other tasks before the calls.

* Fix `condor_submit` and `condor_stop` docstrings

* Update HTCondor runner documentation

Make it clear that the `prefix` is followed by the command without any spaces in between, and thus adding a trailing space to `prefix` is recommended.

* Add new inputs (#204)

* Add new inputs

* frenglish mistake

* new docker version

* Odv : fix path (#205)

* Add new inputs

* frenglish mistake

* new docker version

* Fix broken paths

* fix permission issue for RStudio

* Replace ELIXIR AAI button with Life Science login (#206)

* LS Login button - Update managers.py

ELIXIR AAI (orange) -> LS Login (white/blue)

* LS Login button - Update oidc_backends_config.xml.sample

ELIXIR AAI (orange) -> LS Login (white/blue)

* Holoviz GxIT (#207)

* Add holoviz tool

* holoviz docker of quay.io

* Holoviz fix a docker version issue (#208)

* Add holoviz tool

* holoviz docker of quay.io

* unwanted v in version

* Fix metadata error for hdf files

This should fix the error reported by Wendy.

TypeError: Cannot compare structured or void to non-void arrays.

* add multiple input files

* typo fix

---------

Co-authored-by: Gianmauro Cuccuru <gmauro@gmail.com>
Co-authored-by: Helena Rasche <hxr@hx42.org>
Co-authored-by: Bjoern Gruening <bjoern.gruening@gmail.com>
Co-authored-by: Anup Kumar <kumara@informatik.uni-freiburg.de>
Co-authored-by: davelopez <46503462+davelopez@users.noreply.github.com>
Co-authored-by: Björn Grüning <bjoern@gruenings.eu>
Co-authored-by: José Manuel Domínguez <dominguj@informatik.uni-freiburg.de>
Co-authored-by: Yvan Le Bras <yvan.le-bras@mnhn.fr>
Co-authored-by: Lucille Delisle <lucille.delisle@epfl.ch>
Co-authored-by: Mira <86979912+mira-miracoli@users.noreply.github.com>
Co-authored-by: Anne Fouilloux <annef@simula.no>
Co-authored-by: José Manuel Domínguez <43052541+kysrpex@users.noreply.github.com>
Co-authored-by: sebastian-schaaf <128363933+sebastian-schaaf@users.noreply.github.com>